import type { LocaleTemplates } from './types';

export const en: LocaleTemplates = {
  openingByType: {
    villa: [
      'A composed waterfront villa where the garden ends at the water itself.',
      'This villa sits directly on the waterline, with the shore reached in a few steps.',
      'A light-filled villa built around its water frontage rather than a view of it.',
      'A private villa whose days are organised around the water at the end of the lawn.',
      'A villa of quiet proportions holding a rare stretch of private shoreline.',
      'This is a villa bought for its water: everything else is a bonus.',
    ],
    estate: [
      'A waterfront estate of genuine scale, held behind gates with its own shoreline.',
      'An established estate whose grounds run without interruption to the water.',
      'A generational estate where the shoreline is part of the title, not the scenery.',
      'This estate pairs serious acreage with a working private waterfront.',
      'A rare single-title estate with the water as its fourth boundary.',
    ],
    private_island: [
      'A whole private island, sold with every metre of its own shoreline.',
      'An island in single ownership: the water is not the boundary but the address.',
      'This private island offers the simplest waterfront arithmetic there is — all of it.',
      'A self-contained island estate reached only by boat.',
    ],
    boathouse: [
      'A converted boathouse standing where the water begins, with direct launch from the lower level.',
      'A true boathouse property: the water is under the building, not beyond the garden.',
      'This boathouse pairs simple living space above with working water access below.',
    ],
    _: [
      'A waterfront home where the shoreline belongs to the title.',
      'A property organised entirely around its direct water access.',
      'A home whose defining feature is the water it stands on.',
      'This is a listing for buyers who measure a home in metres of shoreline.',
      'A rare direct-waterfront holding in a market that mostly sells views.',
    ],
  },
  positioning: [
    'It stands in a quiet position at {locality}, facing open water.',
    'The setting is {locality} at its calmest, away from the through-roads.',
    'It occupies one of the last first-line positions in {locality}.',
    'The property sits low to the water on a protected stretch of {locality}.',
    'Its position in {locality} is the kind that no longer gets planning consent.',
    'The approach through {locality} gives no hint of the water frontage behind the gate.',
  ],
  waterSentence: [
    'The property holds {frontage} metres of private {waterBody} frontage, with {beachType} shoreline reached directly from the garden.',
    'There are {frontage} metres of owned {waterBody} shoreline here, {beachType} underfoot and completely private.',
    'Its {frontage}-metre frontage on the {waterBody} is the headline: {beachType} shore, entered from the lawn.',
    '{frontage} metres of {waterBody} waterline belong to the title, with a {beachType} shore below the terrace.',
    'The {beachType} shoreline runs for {frontage} private metres along the {waterBody}.',
    'Frontage measures {frontage} metres on the {waterBody} — {beachType}, private, and usable.',
  ],
  waterSentenceNoFrontage: [
    'Access to the {waterBody} is direct via {access}, with the waterline effectively at the boundary.',
    'The {waterBody} is reached immediately through {access} — no road, no path, no interruption.',
    'Water access is by {access} straight onto the {waterBody}.',
    'The property meets the {waterBody} through its {access}.',
  ],
  accommodationSentence: [
    'Inside are {bedrooms} bedrooms and {bathrooms} bathrooms across {builtArea} m² of accommodation.',
    'The house offers {builtArea} m² arranged as {bedrooms} bedrooms and {bathrooms} bathrooms.',
    'Accommodation runs to {builtArea} m², with {bedrooms} bedrooms, {bathrooms} bathrooms and generous living space toward the water.',
    '{bedrooms} bedrooms and {bathrooms} bathrooms occupy {builtArea} m², most rooms holding a water aspect.',
    'The interior measures {builtArea} m² — {bedrooms} bedrooms, {bathrooms} bathrooms, and principal rooms opening waterside.',
  ],
  outdoorSentence: [
    'Outside, {terrace} m² of terracing steps down toward the shore within grounds of {plotArea} m².',
    'The plot of {plotArea} m² is landscaped to keep the water in view, with {terrace} m² of terraces.',
    'Grounds of {plotArea} m² wrap the house, the {terrace} m² main terrace facing the water.',
    'Terraces of {terrace} m² carry outdoor living to the water’s edge of the {plotArea} m² plot.',
  ],
  nauticalSentence: [
    'The berth takes a boat of up to {loa} metres, with {depth} metres of depth alongside.',
    'Boats to {loa} m lie alongside in {depth} m of water — arrival by sea is the intended entrance.',
    'Mooring is private, for a boat of up to {loa} metres in {depth} metres of water.',
    'Its own berth accepts {loa} metres of boat at {depth} metres of depth.',
  ],
  locationSentence: [
    '{marina} lies {marinaKm} km away for fuel, service and winter storage.',
    'The nearest full-service marina, {marina}, is {marinaKm} km by water.',
    'Everyday boating support is at {marina}, {marinaKm} km from the property.',
    'For provisioning afloat, {marina} sits {marinaKm} km along the shore.',
  ],
  closingByTier: {
    standard: [
      'A practical entry into true waterfront ownership in {destination}.',
      'One of the more attainable direct-water holdings currently offered in {destination}.',
      'A sensible first waterfront purchase in {destination}.',
    ],
    premium: [
      'A serious waterfront holding in one of {destination}’s established first-line addresses.',
      'The kind of {destination} waterfront that changes hands quietly, and rarely.',
      'A confident purchase in the strongest segment of the {destination} market.',
    ],
    trophy: [
      'Among the few genuinely irreplaceable waterfront properties in {destination}.',
      'A generational acquisition on {destination}’s most protected stretch of water.',
      'For the shortlist of buyers to whom {destination} means this exact shoreline.',
    ],
  },
  titleByType: {
    villa: [
      'Villa with {access} in {locality}',
      'Waterfront villa with {frontage} m of frontage, {locality}',
      'Villa on the {waterBody} at {locality}',
    ],
    estate: [
      'Waterfront estate with {access}, {locality}',
      'Estate with {frontage} m of private shoreline, {locality}',
    ],
    private_island: ['Private island off {locality}', 'Whole island with {frontage} m of shore, {locality}'],
    boathouse: ['Boathouse on the {waterBody}, {locality}'],
    marina_residence: ['Marina residence with {loa} m berth, {locality}'],
    penthouse: ['Waterfront penthouse in {locality}'],
    apartment: ['Waterside apartment with {access}, {locality}'],
    townhouse: ['Canal-side townhouse in {locality}', 'Townhouse on the water, {locality}'],
    chalet: ['Waterfront chalet in {locality}', 'Chalet on the {waterBody}, {locality}'],
    farmhouse: ['Waterfront farmhouse near {locality}'],
    _: ['Waterfront property with {access} in {locality}'],
  },
  words: {
    beachType: { sand: 'sand', pebble: 'pebble', rock: 'rock', mixed: 'mixed', none: 'natural' },
    access: {
      private_beach: 'a private beach',
      shared_beach: 'a shared beach',
      direct_shore: 'direct shore access',
      private_dock: 'a private dock',
      private_mooring: 'a private mooring',
      marina_berth_included: 'an included marina berth',
      boathouse: 'a boathouse',
      slipway: 'a slipway',
      seawall_quay: 'a quay wall',
      rock_platform: 'a rock platform',
      riparian_access: 'riparian access',
      whole_island: 'whole-island ownership',
    },
  },
};
