/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    properties: Property;
    agencies: Agency;
    agents: Agent;
    'water-bodies': WaterBody;
    destinations: Destination;
    leads: Lead;
    'landing-pages': LandingPage;
    taxonomies: Taxonomy;
    articles: Article;
    pages: Page;
    redirects: Redirect;
    'audit-logs': AuditLog;
    'import-jobs': ImportJob;
    'consent-records': ConsentRecord;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    agencies: AgenciesSelect<false> | AgenciesSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    'water-bodies': WaterBodiesSelect<false> | WaterBodiesSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    taxonomies: TaxonomiesSelect<false> | TaxonomiesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'import-jobs': ImportJobsSelect<false> | ImportJobsSelect<true>;
    'consent-records': ConsentRecordsSelect<false> | ConsentRecordsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'it' | 'fr' | 'de' | 'es' | 'ru')
    | ('en' | 'it' | 'fr' | 'de' | 'es' | 'ru')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'it' | 'fr' | 'de' | 'es' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'agency_admin' | 'agency_agent';
  /**
   * Required for agency roles. Scopes every query they make.
   */
  agency?: (number | null) | Agency;
  /**
   * Links an agency_agent user to their public agent profile for lead routing and "own listings" scoping.
   */
  agentProfile?: (number | null) | Agent;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies".
 */
export interface Agency {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  description?: string | null;
  /**
   * ISO-3166-1 alpha-2.
   */
  country?: string | null;
  languages?: ('en' | 'it' | 'fr' | 'de' | 'es' | 'ru')[] | null;
  website?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  email?: string | null;
  licenceNumber?: string | null;
  verified?: boolean | null;
  verifiedAt?: string | null;
  /**
   * verified tier auto-approves listings that pass automated validation (§8.2).
   */
  tier?: ('standard' | 'verified' | 'partner') | null;
  listingQuota?: number | null;
  /**
   * Inbound feed configuration (§8.5). Polled every 6 h.
   */
  feed?: {
    feedUrl?: string | null;
    /**
     * Per-agency ingest token.
     */
    feedToken?: string | null;
    feedFormat?: ('native_json' | 'kyero_xml' | 'resales_online' | 'houzez_wp' | 'generic_csv') | null;
    feedLastRunAt?: string | null;
    feedLastStatus?: string | null;
    /**
     * Source-field → schema mapping for generic feeds (§8.5).
     */
    fieldMapping?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Set automatically for agency uploads. Scopes edit access.
   */
  agency?: (number | null) | Agency;
  credit?: string | null;
  /**
   * Licence position for this asset (§13.2), e.g. "agency-supplied", "Unsplash".
   */
  licence?: string | null;
  sourceUrl?: string | null;
  /**
   * Source-API photo id (§13.2.3) — powers dedupe and purge.
   */
  sourceId?: string | null;
  blurhash?: string | null;
  dominantColor?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    w320?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w640?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w960?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w1280?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w1920?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w2560?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: number;
  name: string;
  agency: number | Agency;
  photo?: (number | null) | Media;
  /**
   * e.g. "Senior Partner".
   */
  role?: string | null;
  languages?: ('en' | 'it' | 'fr' | 'de' | 'es' | 'ru')[] | null;
  phone?: string | null;
  whatsapp?: string | null;
  email?: string | null;
  receivesLeads?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A listing publishes only with at least one water access type and distance to water ≤ 50 m. This rule is the brand. Brochure PDF for any published listing: /api/property/{slug}/brochure.pdf?locale=en
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  title: string;
  subtitle?: string | null;
  /**
   * The agency's own listing code. Unique per agency.
   */
  reference?: string | null;
  propertyType:
    | 'villa'
    | 'apartment'
    | 'penthouse'
    | 'estate'
    | 'farmhouse'
    | 'chalet'
    | 'townhouse'
    | 'castle'
    | 'lighthouse'
    | 'boathouse'
    | 'private_island'
    | 'land_plot'
    | 'marina_residence'
    | 'development_project'
    | 'hotel_resort';
  priceType: 'fixed' | 'on_request' | 'auction' | 'poa';
  priceAmount?: number | null;
  currency: 'EUR' | 'USD' | 'GBP' | 'CHF' | 'AED' | 'SGD';
  priceQualifier?: ('guide' | 'asking' | 'offers_over' | 'reduced') | null;
  tenure?: ('freehold' | 'leasehold' | 'concession' | 'fractional' | 'share_transfer') | null;
  leaseYearsRemaining?: number | null;
  serviceChargeAnnual?: number | null;
  propertyTaxAnnual?: number | null;
  availableFrom?: string | null;
  waterBodyType:
    | 'sea'
    | 'ocean'
    | 'lake'
    | 'river'
    | 'lagoon'
    | 'canal'
    | 'fjord'
    | 'bay'
    | 'estuary'
    | 'reservoir'
    | 'marina_basin';
  /**
   * Controlled name: "Ligurian Sea", "Lake Como", …
   */
  waterBody?: (number | null) | WaterBody;
  /**
   * At least one is required to publish. "Sea view" and "near the beach" do not qualify.
   */
  waterAccessType?:
    | (
        | 'private_beach'
        | 'shared_beach'
        | 'direct_shore'
        | 'private_dock'
        | 'private_mooring'
        | 'marina_berth_included'
        | 'boathouse'
        | 'slipway'
        | 'seawall_quay'
        | 'rock_platform'
        | 'riparian_access'
        | 'whole_island'
      )[]
    | null;
  /**
   * Metres from the property boundary to the waterline. Above 50 m the listing cannot publish.
   */
  distanceToWaterM?: number | null;
  /**
   * ⚠ Linear metres of private shoreline — the headline card stat. Cards and ranking suffer without it; fill it whenever the shoreline is private.
   */
  waterFrontageM?: number | null;
  beachType?: ('sand' | 'pebble' | 'rock' | 'mixed' | 'none') | null;
  orientation?: ('N' | 'NE' | 'E' | 'SE' | 'S' | 'SW' | 'W' | 'NW') | null;
  swimmableFromProperty?: boolean | null;
  tidal?: boolean | null;
  tideRangeM?: number | null;
  waterfrontProtection?: ('natural' | 'seawall' | 'riprap' | 'breakwater' | 'pier_only') | null;
  /**
   * Local designation verbatim; shown with a disclaimer.
   */
  floodZone?: string | null;
  /**
   * In Italy this is the demanio marittimo question — it materially changes value.
   */
  shorelineTenure?:
    | ('private_to_waterline' | 'private_to_high_water' | 'public_easement' | 'state_concession' | 'riparian_rights')
    | null;
  concessionExpiry?: string | null;
  mooringType?:
    | (
        | 'none'
        | 'buoy'
        | 'jetty'
        | 'pontoon'
        | 'fixed_dock'
        | 'floating_dock'
        | 'boat_lift'
        | 'dry_dock'
        | 'marina_berth'
      )
    | null;
  berthCount?: number | null;
  maxBoatLoaM?: number | null;
  maxBoatBeamM?: number | null;
  waterDepthAtBerthM?: number | null;
  navigableToOpenSea?: boolean | null;
  fixedBridgesToOpenSea?: boolean | null;
  minBridgeClearanceM?: number | null;
  nearestMarinaName?: string | null;
  nearestMarinaDistanceKm?: number | null;
  shorePower?: boolean | null;
  freshWaterAtDock?: boolean | null;
  fuelDockNearby?: boolean | null;
  helipad?: boolean | null;
  seaplaneAccess?: boolean | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  builtAreaSqm?: number | null;
  plotAreaSqm?: number | null;
  terraceAreaSqm?: number | null;
  yearBuilt?: number | null;
  renovatedYear?: number | null;
  floors?: number | null;
  parkingSpaces?: number | null;
  condition?: ('new' | 'renovated' | 'good' | 'to_renovate' | 'shell') | null;
  energyRating?: string | null;
  features?:
    | (
        | 'pool'
        | 'infinity_pool'
        | 'heated_pool'
        | 'gym'
        | 'spa'
        | 'sauna'
        | 'staff_quarters'
        | 'helipad'
        | 'tennis'
        | 'vineyard'
        | 'olive_grove'
        | 'solar'
        | 'geothermal'
        | 'elevator'
        | 'gated'
        | 'smart_home'
        | 'guest_house'
        | 'garage'
        | 'wine_cellar'
        | 'cinema'
      )[]
    | null;
  location?: {
    label?: string | null;
    /**
     * Admin-only. Never rendered publicly.
     */
    addressLine?: string | null;
    locality?: string | null;
    province?: string | null;
    region?: string | null;
    /**
     * ISO-3166-1 alpha-2, e.g. IT, FR, US.
     */
    country?: string | null;
    continent?: string | null;
    /**
     * @minItems 2
     * @maxItems 2
     */
    coordinates?: [number, number] | null;
    /**
     * approximate_500m renders a jittered circle publicly; exact coordinates never reach the client for those listings.
     */
    coordinatePrecision?: ('exact' | 'approximate_500m' | 'hidden') | null;
    destination?: (number | null) | Destination;
  };
  /**
   * Ordered. The first image is the hero and card image.
   */
  media?: (number | Media)[] | null;
  videoUrl?: string | null;
  virtualTourUrl?: string | null;
  floorplans?: (number | Media)[] | null;
  /**
   * Private — admin and owning agency only. Never public.
   */
  documents?: (number | Media)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * Generated on first publish. Immutable — changes create a Redirect.
   */
  slug?: string | null;
  /**
   * Multi-tenancy key. Every query is scoped by it.
   */
  agency: number | Agency;
  /**
   * Lead routing target.
   */
  agent?: (number | null) | Agent;
  status: 'draft' | 'pending_review' | 'in_market' | 'under_offer' | 'sold' | 'withdrawn' | 'expired' | 'archived';
  moderation: 'unreviewed' | 'approved' | 'rejected' | 'changes_requested';
  /**
   * Shown to the agency. Not public.
   */
  moderationNote?: string | null;
  /**
   * unlisted = link-only, noindex, out of sitemap.
   */
  visibility: 'public' | 'unlisted' | 'private';
  /**
   * Editorial only. Agencies cannot self-feature.
   */
  featured?: boolean | null;
  /**
   * Demo data: SAMPLE badge, noindex, out of sitemaps.
   */
  isSample?: boolean | null;
  /**
   * Computed from the daily FX snapshot. The only field used for price sorting/filtering.
   */
  priceEur?: number | null;
  publishedAt?: string | null;
  /**
   * publishedAt + 180 days unless the agency reconfirms availability.
   */
  expiresAt?: string | null;
  /**
   * Set when the agency confirms the listing is still available.
   */
  lastVerifiedAt?: string | null;
  /**
   * When the §8.7 T-14 confirmation email last went out.
   */
  expiryReminderSentAt?: string | null;
  sourceType: 'manual' | 'csv_import' | 'xml_feed' | 'api';
  /**
   * Set by duplicate detection (§8.8).
   */
  duplicateOf?: (number | null) | Property;
  fingerprint?: string | null;
  viewCount?: number | null;
  leadCount?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "water-bodies".
 */
export interface WaterBody {
  id: number;
  name: string;
  slug: string;
  type?:
    | (
        | 'sea'
        | 'ocean'
        | 'lake'
        | 'river'
        | 'lagoon'
        | 'canal'
        | 'fjord'
        | 'bay'
        | 'estuary'
        | 'reservoir'
        | 'marina_basin'
      )
    | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  name: string;
  slug: string;
  country?: string | null;
  region?: string | null;
  heroImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  message?: string | null;
  property?: (number | null) | Property;
  /**
   * Denormalised for routing and access scoping.
   */
  agency?: (number | null) | Agency;
  /**
   * Routing target snapshot (property.agent at submission time).
   */
  agent?: (number | null) | Agent;
  locale?: ('en' | 'it' | 'fr' | 'de' | 'es' | 'ru') | null;
  source: 'contact' | 'property' | 'landing' | 'boat_filter' | 'whatsapp' | 'list_with_us';
  status: 'new' | 'sent' | 'viewed' | 'qualified' | 'spam';
  consent?: {
    consentMarketing?: boolean | null;
    consentedAt?: string | null;
    consentIp?: string | null;
  };
  /**
   * When the §8.9 48 h unanswered reminder went out.
   */
  reminderSentAt?: string | null;
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Reserved (empty in Phase 1).
   */
  navigationPath?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Reserved for the Phase 2 CRM seam.
   */
  crmContactId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: number;
  title: string;
  slug: string;
  /**
   * The filter combination this page targets.
   */
  combo?: {
    propertyType?:
      | (
          | 'villa'
          | 'apartment'
          | 'penthouse'
          | 'estate'
          | 'farmhouse'
          | 'chalet'
          | 'townhouse'
          | 'castle'
          | 'lighthouse'
          | 'boathouse'
          | 'private_island'
          | 'land_plot'
          | 'marina_residence'
          | 'development_project'
          | 'hotel_resort'
        )
      | null;
    waterBodyType?:
      | (
          | 'sea'
          | 'ocean'
          | 'lake'
          | 'river'
          | 'lagoon'
          | 'canal'
          | 'fjord'
          | 'bay'
          | 'estuary'
          | 'reservoir'
          | 'marina_basin'
        )
      | null;
    destination?: (number | null) | Destination;
    country?: string | null;
  };
  /**
   * Opens with a 40–60-word direct answer paragraph (§14.6). Required before the combo goes live.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Question-form entries rendered as an accordion with FAQPage JSON-LD (§10.4/§14.3). Answer real buyer questions — mooring rules, tenure, access.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomies".
 */
export interface Taxonomy {
  id: number;
  name: string;
  slug: string;
  group: 'lifestyle' | 'style' | 'collection';
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | User;
  publishedAt?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: string | null;
  statusCode: '301' | '302' | '410';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: 'create' | 'update' | 'delete' | 'publish' | 'lead_view' | 'lead_anonymized' | 'status_change';
  targetCollection: string;
  targetId: string;
  summary?: string | null;
  actor?: (number | null) | User;
  actorEmail?: string | null;
  actorRole?: string | null;
  agency?: (number | null) | Agency;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-jobs".
 */
export interface ImportJob {
  id: number;
  agency: number | Agency;
  sourceFilename?: string | null;
  kind?: ('csv' | 'xlsx' | 'feed') | null;
  status: 'queued' | 'dry_run' | 'running' | 'complete' | 'failed';
  rowsProcessed?: number | null;
  rowsFailed?: number | null;
  /**
   * Row-by-row ok/warning/error with the exact reason and column (§8.4).
   */
  errorReport?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records".
 */
export interface ConsentRecord {
  id: number;
  analytics: boolean;
  marketing: boolean;
  locale?: string | null;
  ipHash?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'agencies';
        value: number | Agency;
      } | null)
    | ({
        relationTo: 'agents';
        value: number | Agent;
      } | null)
    | ({
        relationTo: 'water-bodies';
        value: number | WaterBody;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null)
    | ({
        relationTo: 'taxonomies';
        value: number | Taxonomy;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'import-jobs';
        value: number | ImportJob;
      } | null)
    | ({
        relationTo: 'consent-records';
        value: number | ConsentRecord;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  agency?: T;
  agentProfile?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  agency?: T;
  credit?: T;
  licence?: T;
  sourceUrl?: T;
  sourceId?: T;
  blurhash?: T;
  dominantColor?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        w320?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w640?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w960?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w1280?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w1920?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w2560?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  reference?: T;
  propertyType?: T;
  priceType?: T;
  priceAmount?: T;
  currency?: T;
  priceQualifier?: T;
  tenure?: T;
  leaseYearsRemaining?: T;
  serviceChargeAnnual?: T;
  propertyTaxAnnual?: T;
  availableFrom?: T;
  waterBodyType?: T;
  waterBody?: T;
  waterAccessType?: T;
  distanceToWaterM?: T;
  waterFrontageM?: T;
  beachType?: T;
  orientation?: T;
  swimmableFromProperty?: T;
  tidal?: T;
  tideRangeM?: T;
  waterfrontProtection?: T;
  floodZone?: T;
  shorelineTenure?: T;
  concessionExpiry?: T;
  mooringType?: T;
  berthCount?: T;
  maxBoatLoaM?: T;
  maxBoatBeamM?: T;
  waterDepthAtBerthM?: T;
  navigableToOpenSea?: T;
  fixedBridgesToOpenSea?: T;
  minBridgeClearanceM?: T;
  nearestMarinaName?: T;
  nearestMarinaDistanceKm?: T;
  shorePower?: T;
  freshWaterAtDock?: T;
  fuelDockNearby?: T;
  helipad?: T;
  seaplaneAccess?: T;
  bedrooms?: T;
  bathrooms?: T;
  builtAreaSqm?: T;
  plotAreaSqm?: T;
  terraceAreaSqm?: T;
  yearBuilt?: T;
  renovatedYear?: T;
  floors?: T;
  parkingSpaces?: T;
  condition?: T;
  energyRating?: T;
  features?: T;
  location?:
    | T
    | {
        label?: T;
        addressLine?: T;
        locality?: T;
        province?: T;
        region?: T;
        country?: T;
        continent?: T;
        coordinates?: T;
        coordinatePrecision?: T;
        destination?: T;
      };
  media?: T;
  videoUrl?: T;
  virtualTourUrl?: T;
  floorplans?: T;
  documents?: T;
  description?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  slug?: T;
  agency?: T;
  agent?: T;
  status?: T;
  moderation?: T;
  moderationNote?: T;
  visibility?: T;
  featured?: T;
  isSample?: T;
  priceEur?: T;
  publishedAt?: T;
  expiresAt?: T;
  lastVerifiedAt?: T;
  expiryReminderSentAt?: T;
  sourceType?: T;
  duplicateOf?: T;
  fingerprint?: T;
  viewCount?: T;
  leadCount?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies_select".
 */
export interface AgenciesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  description?: T;
  country?: T;
  languages?: T;
  website?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  licenceNumber?: T;
  verified?: T;
  verifiedAt?: T;
  tier?: T;
  listingQuota?: T;
  feed?:
    | T
    | {
        feedUrl?: T;
        feedToken?: T;
        feedFormat?: T;
        feedLastRunAt?: T;
        feedLastStatus?: T;
        fieldMapping?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  name?: T;
  agency?: T;
  photo?: T;
  role?: T;
  languages?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  receivesLeads?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "water-bodies_select".
 */
export interface WaterBodiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  country?: T;
  region?: T;
  heroImage?: T;
  description?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  property?: T;
  agency?: T;
  agent?: T;
  locale?: T;
  source?: T;
  status?: T;
  consent?:
    | T
    | {
        consentMarketing?: T;
        consentedAt?: T;
        consentIp?: T;
      };
  reminderSentAt?: T;
  utm?: T;
  navigationPath?: T;
  crmContactId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  combo?:
    | T
    | {
        propertyType?: T;
        waterBodyType?: T;
        destination?: T;
        country?: T;
      };
  intro?: T;
  body?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomies_select".
 */
export interface TaxonomiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  group?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  author?: T;
  publishedAt?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  targetCollection?: T;
  targetId?: T;
  summary?: T;
  actor?: T;
  actorEmail?: T;
  actorRole?: T;
  agency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-jobs_select".
 */
export interface ImportJobsSelect<T extends boolean = true> {
  agency?: T;
  sourceFilename?: T;
  kind?: T;
  status?: T;
  rowsProcessed?: T;
  rowsFailed?: T;
  errorReport?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records_select".
 */
export interface ConsentRecordsSelect<T extends boolean = true> {
  analytics?: T;
  marketing?: T;
  locale?: T;
  ipHash?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}